### ISSUE TITLE
Is Nodejs certification ever going to be a thing?

### ISSUE THREAD

**Issue by OussamaRomdhane** [nodejs-certified-developer/certification#1]
I live in France and I would like to get certified, as of now, is it clear whether or not we'll have any official certification exams anywhen soon?
Thank you

**Comment by hackygolucky** [comment]
The repo you have filed this issue in is the public facing repo for all the
work happening around this(much in private due to the content). We are
looking at a Q3 release after we are able to get through the beta testing
and QA phases. Stay tuned!

**Comment by OussamaRomdhane** [comment]
Thank you very much for the quick answer I started watching this repo and will sure stay on the watch.
Cheers :smile:
