### ISSUE TITLE
Need Peer Review for PRs for Node Certification Requests

### ISSUE THREAD

**Issue by mrhinkle** [nodejs-certified-developer/certification#10]
Hello, @nodejs-certified-developer/contributors we are getting close to an alpha of Node Certification test but we need some peer reviewers of the test questions and we are putting forth a call for volunteers to help reviewer the PRs against the existing questions. If you'd like to be involved we would be grateful for any help @afisher9 will provide you with an NDA for the questions if you haven't processed one yet.

**Comment by hackygolucky** [comment]
@mrhinkle No one gets access to the private repos(added to the contributors list) until they've signed the NDA, so you should be good on that front. 

If you end up getting new folks from the community, however, they'd need the NDA and the walkthrough onboarding documents to get started.

**Comment by yasinaydin** [comment]
I am interested in testing, how do I sign up and what can I do?

**Comment by lukaszewczak** [comment]
Hi @mrhinkle , @afisher9,  I would like to help with testing.

**Comment by davidmarkclements** [comment]
hey @yasinaydin and @lukaszewczak 

(@afisher9 @mrhinkle correct me if I'm wrong) 

this is specifically a call for *peer reviewers* of the items (an item consists of content *and* code implementation), this is different to alpha testing

**Comment by afisher9** [comment]
@davidmarkclements - yes, thank you David!  This is a call for peer reviews of the existing questions.  If peer reviews are something you'd like to contribute to the process - let me know and we'll get you started in the process.

Cheers - A

**Comment by mrhinkle** [comment]
Yes @davidmarkclements - We are looking for peer reviewers of the PRs not testers at this point.

**Comment by lukaszewczak** [comment]
I apologize for the confusion.

**Comment by yasinaydin** [comment]
I can also help with the peer reviews and can sign NDA.

**Comment by terary** [comment]
I can help anyway you need

**Comment by ErickWendel** [comment]
I can help, but I would know if we help in reviews we can do the certification after (because we will access for the questions and maybe after assign NDA we can't do this challenge)

**Comment by afisher9** [comment]
Greetings Igor,

That's great news!  Apologies for the delay in response.  Could you send me
your email address so I may send over the NDA for your signature?

So excited to have you on board.

Cheers,
Annie

Annie Fisher, MPA CSM
Program Manager, The Linux Foundation
Location & Time-zone: San Francisco, CA, PT
web: https://www.linuxfoundation.org/
email: afisher@linuxfoundation.org

**Comment by afisher9** [comment]
Greeting Terry,

Thank you! Having the community assist is just about as good as it gets!!

Could I get your email address so I may send over the NDA for your
signature?

Cheers,
Annie
Annie Fisher, MPA CSM
Program Manager, The Linux Foundation
Location & Time-zone: San Francisco, CA, PT
web: https://www.linuxfoundation.org/
email: afisher@linuxfoundation.org

**Comment by afisher9** [comment]
Greetings Erick,

We'd love to have any assistance you could provide, but totally understand
if you'd rather wait to be able to take the exam yourself...that would be
our priority!

Let me know and if you would like to help with the pull requests, could I
get your email address so I may send over the NDA agreement.

Thanks and hope you're doing well.
Annie
Annie Fisher, MPA CSM
Program Manager, The Linux Foundation
Location & Time-zone: San Francisco, CA, PT
web: https://www.linuxfoundation.org/
email: afisher@linuxfoundation.org

**Comment by terary** [comment]
Annie,

My e.mail address is terary@gmail.com
Also please note that my e.mail address and first name have an 'A'
 Terary

Kind regards
T. Chambers

**Comment by ErickWendel** [comment]
Annie, 
Count on me! My email is erick.workspace@gmail.com

**Comment by Horaddrim** [comment]
Hi there! Let's rock!! 🤘🤘 My email is lee12rock@gmail.com

**Comment by ibotirama** [comment]
Hi there! My email is pedro.henrique1@gmail.com, I want to participate too, let's rock!

**Comment by vvscode** [comment]
I'm ready to help (NDA is by default for such cases)

**Comment by yasinaydin** [comment]
Hello, my email is yasin@yasinaydin.net

**Comment by terary** [comment]
Just as matter of curiosity, do have any notions about scheduling? When should be expect materials and/or deadlines for completion?
