### ISSUE TITLE
Is Node.js Certification based on Node.js Core modules?

### ISSUE THREAD

**Issue by lukaszewczak** [nodejs-certified-developer/certification#15]
Hi,

I looked at the final topics which certification will cover, but it is not clear to me if this test will be based only on Node.js Core modules, or it will assume using modules from npm? Could you please clarify this. For example, if unit testing will be based only on built-in `assert` module or assume using testing frameworks like `Mocha` for example, where with security topic some npm tools can be used (probably for security section this page https://nodesecroadmap.fyi/ , will be good to train).

Thank you in advance for your answer

Regards,
Łukasz

**Comment by davidmarkclements** [comment]
This is a very delicate discussion to have publically because it's important not to overreveal. While I can answer this question I'm uncertain whether I can do so. @mrhinkle am I ok to answer?

**Comment by lukaszewczak** [comment]
Hi @davidmarkclements, I'm aware that this is a delicate topic, but are you able to put some light on it?

Thank you.

**Comment by davidmarkclements** [comment]
@lukaszewczak - referring you to @mrhinkle to confirm whether I'm ok to answer.

**Comment by lukaszewczak** [comment]
Hello, @davidmarkclements ,
Just a friendly reminder :-) . Thank you.

**Comment by mrhinkle** [comment]
The focus is on core modules but it  is also about problem solving, the candidate may or may not use core modules to solve the problem. In the testing environment you may use ecosystem modules.
